import { App, PluginSettingTab, Setting } from "obsidian";
import { MDPSettings } from "./settings";

/** Minimal interface so settingsTab doesn't create a circular import with main.ts */
interface MDPPluginHost {
	app: App;
	settings: MDPSettings;
	saveSettings(): Promise<void>;
	applyStyles(): void;
}

export class MDPSettingTab extends PluginSettingTab {
	plugin: MDPPluginHost;

	constructor(app: App, plugin: MDPPluginHost) {
		super(app, plugin as never);
		this.plugin = plugin;
	}

	display(): void {
		const { containerEl } = this;
		containerEl.empty();

		containerEl.createEl("p", {
			text: "Tint colors applied in both Reading and Live Preview modes. Self-authored text is always unstyled — it's the baseline.",
			cls: "setting-item-description",
		});

		this.addColorSetting(
			"Assistant",
			"Text generated by an AI assistant  (%a{...})",
			"assistant"
		);
		this.addColorSetting(
			"Quote",
			"Text from a third-party source  (%q{...})",
			"quote"
		);
		this.addColorSetting(
			"Unknown",
			"Text of unclear provenance  (%u{...})",
			"unknown"
		);

		containerEl.createEl("p", {
			text: 'Changes take effect immediately. Reload the plugin to reset to defaults.',
			cls: "setting-item-description",
		});
	}

	private addColorSetting(
		name: string,
		desc: string,
		key: keyof MDPSettings["colors"]
	): void {
		new Setting(this.containerEl)
			.setName(name)
			.setDesc(desc)
			.addText((text) => {
				text.inputEl.type = "color";
				text.inputEl.value = this.plugin.settings.colors[key];
				text.inputEl.style.width = "4rem";
				text.inputEl.style.padding = "0";
				text.inputEl.style.cursor = "pointer";
				text.inputEl.addEventListener("input", async () => {
					this.plugin.settings.colors[key] = text.inputEl.value;
					await this.plugin.saveSettings();
					this.plugin.applyStyles();
				});
			});
	}
}
